spring:
  application:
    name: EventClean
  datasource:
    url: jdbc:postgresql://localhost:5432/event-clean-db
    username: admin
    password: adminsenha
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration